### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Alberto4774** [smislav/iota-poker-issues#1]
- Make bet/check/fold buttons bigger and below the table instead of below player
- Sound effects (alarm when close to timeout, chip sound when bet, check sounds, cards dealed sound, etc...)
- Option to type amount of mi that want to raise + clicking adds 1mi instead of 0.01mi
- option to bet % of pot amounts (and option to edit this %)
- Replayer
- Chips animations + cards animations when dealed
- When all in, deal flop/turn/river slower + add % of equity of each player
- Option to note players
- When reraising, reraise to the amount selected instead of amount selected+bet of rival
- Add other game types? Maybe sit and go or mtt
- Add tymer of time left to action
- Add option to premove
- Option to show balance
- Option to auto sitout next bb

**Comment by smislav** [comment]
Thanks, Ill move that to the roadmap
