### ISSUE TITLE
sent tokens not appearing in profile

### ISSUE THREAD

**Issue by IGit666** [smislav/iota-poker-issues#2]
Sent 75 devnet tokens, confirmed in firefly, but hitting refresh on the site doesn't show a balance (see the green success checkmark in upper right of screen). 

Edited to add screenshots, at the time trying to transfer, it was showing the green success checkmark. Today when I went to that page it shows an error code that you can see in the screenshot. The email I signed up with was iotapoker@sharklasers.com

![iotapokerscrnsht](https://user-images.githubusercontent.com/39487435/148776222-96302925-ab7c-4d3b-8fab-a9126b50476a.jpg)
![iotapokerscrnsht2](https://user-images.githubusercontent.com/39487435/148776228-c5e2f84a-7dad-41af-844a-603523b74a6d.jpg)

**Comment by smislav** [comment]
please send a screenshot and your email user for registration

**Comment by IGit666** [comment]
successfully sent 125 mi, but the initial 75 mi still doesn't show, should be a total of 200 but there is only 125.

**Comment by smislav** [comment]
I have checked this and 75 Mi is in the wallet, the system just didn't update your account.
A possible reason is found and will fix it, thanks!
