### ISSUE TITLE
Over credit of funds

### ISSUE THREAD

**Issue by CetParibus** [smislav/iota-poker-issues#4]
It appears that I have been able to withdraw my ballance twice. Is it possible that your hotwallet is short? The amount is 150Miota

**Comment by smislav** [comment]
@CetParibus I can see two withdrawals of -150 Mi, 15 minutes difference in time.
But only the latest one is registered in the database. That means that the first request was taken from hot wallet but wasn't subtracted from your account.

Did you get maybe a timeout error or something similar for the first request?

**Comment by CetParibus** [comment]
It was late when I did the first withdrawal. Went to sleep and in the morning checked and found the balance was still in my iotapoker account. Thought it would clear up if I tried to withdraw, but I got a double hit. How can I help to resolve this. Don't want to harm the project by stealing from you.

**Comment by CetParibus** [comment]
No timeout error. The balance just wouldn't update to show the withdrawal. I had it in Firefly. Perhaps, I tried it again that night to a tanglepay wallet. It was late, so a bit hazzy on the details on my end.

**Comment by smislav** [comment]
@CetParibus I have made some changes and hopefully this won't happen again. I think you can't help much now, but anyway thanks for reporting this, not a minor issue. I'll have to monitor this.

If you want you can donate a faulty amount to the address visible in the lobby, or if you want to keep it as a reward I am ok with that.
